version: "3"

services:
  ai-server:
    image: ghcr.io/seoulsky/desdemona-ai:latest
    container_name: ai-server
    ports:
      - "8000:8000"
  web-server:
    image: ghcr.io/seoulsky/desdemona-web:latest
    container_name: web-server
    depends_on:
     - ai-server
    ports:
     - "80:8080"
