version: "3"

services:
  ai-server:
    image: ghcr.io/seoulsky/desdemona-ai:latest
    container_name: ai-server
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./ai-server:/app

  web-server:
    image: ghcr.io/seoulsky/desdemona-web:latest
    container_name: web-server
    restart: unless-stopped
    depends_on:
      - ai-server
    ports:
      - 8080:8080
    environment:
      - PRODUCTION=true

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
