version: "3"

services:
  ai-server:
    image: ghcr.io/seoulsky/desdemona-ai:latest
    container_name: ai-server
    ports:
      - "8000:8000"
  web-server:
    image: ghcr.io/seoulsky/desdemona-web:latest
    container_name: web-server
    depends_on:
     - ai-server
    ports:
     - "8080:8080"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-server
      - ai-server
