version: "3"

services:
  ai-server:
    image: ghcr.io/seoulsky/desdemona-ai:latest
    container_name: ai-server
    ports:
      - 8000:8000
    volumes:
      - ./ai-server:/app
  web-server:
    image: ghcr.io/seoulsky/desdemona-web:latest
    container_name: web-server
    depends_on:
     - ai-server
    ports:
     - 8080:8080
    environment:
      - PRODUCTION=true
