name: Build and Push Docker Images

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker:
    environment: desdemona
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ai-server image
        id: meta_ai
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/desdemona-ai

      - name: Build and push ai-server
        uses: docker/build-push-action@v4
        with:
          context: ai-server
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta_ai.outputs.tags }}
          labels: ${{ steps.meta_ai.outputs.labels }}

      - name: Extract metadata for web-server image
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/desdemona-web

      - name: Build and push web-server
        uses: docker/build-push-action@v4
        with:
          context: web-server
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
