name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    environment: desdemona
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Repository Name in Lowercase
      id: repo_name
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}

    - name: Build and push ai-server
      uses: docker/build-push-action@v4
      with:
        context: ai-server
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: |
          ghcr.io/${{ steps.repo_name.outputs.lowercase }}-ai:latest

    - name: Build and push web-server
      uses: docker/build-push-action@v4
      with:
        context: web-server
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: |
          ghcr.io/${{ steps.repo_name.outputs.lowercase }}-web:latest
